Assets/Scenes/MovementTestScene.unity
Assets/Scenes/MovementTestScene.unity.meta
Assets/Scripts/Player/Movement.cs
Assets/Scripts/Player/PlayerControls.cs

Changes
* added WASD movement, jump and basic dash
* created basic test area

added movement from game jam, created basic test area

---

Assets/Scripts/Enemy.meta
Assets/Scripts/Enemy/EnemyBehaviour.cs
Assets/Scripts/Enemy/EnemyBehaviour.cs.meta
Assets/Scripts/Enemy/EnemyFactory.cs
Assets/Scripts/Enemy/EnemyFactory.cs.meta

Implemented a framework for our enemy AI. 
The expected flow:
1. The spawning mechanism utilizes EnemyFactory by passing a name of a prefab (enemy) and position to EnemyFactory.CreateEnemy(). TODO: Currently targeting, moving, and pathfinding is defaulted, but we have the ability to dynamically change it easily. We need to determine how we want to set those up.
2. EnemyFactory instantiates the prefab and sets its location, then calls EnemyBehaviour.AddToGameObject() with the dynamic modules (pathfinding, moving, aiming).
3. EnemyBehaviour.AddToGameObject() adds the EnemyBehaviour script as a component to the prefab/game object, then initializes the EnemyBehaviour with the dynamic module arguments.
4. EnemyFactory calls additional setup from _enemySetups if any exist or are required. …

Implement enemy behaviour framework

---

Assets/Scripts/Enemy/EnemyBehaviour.cs
Assets/Scripts/Enemy/EnemyFactory.cs
Assets/Scripts/EnemySpawn.cs
Assets/Scripts/Globals.cs
Assets/Scripts/Player/PlayerControls.cs
Assets/Scripts/Stats.cs
Assets/Scripts/Weapons/BehaviourTypes/BulletBehaviour.cs
Assets/Scripts/Weapons/BehaviourTypes/BulletMono.cs
Assets/Scripts/Weapons/IHitBehaviour.cs
Assets/Scripts/Weapons/Weapon.cs

* Refactored Weapon away from MonoBehaviour
* Added EntityType as global, added owner attribute to the now abstract HitBehaviour, added EntityType type to Stats
* Implemented Direct Targeting in Globals and used it as the default aim
Added a few TODOs.
Closes #5

Implement enemy attacking

---

Assets/Resources/Player/Player.prefab
Assets/Resources/Player/Player.prefab.meta
Assets/Scenes/LevelPrototypeScene.unity
Assets/Scripts/Player/Movement.cs
Assets/Scripts/Player/PlayerControls.cs
Assets/Scripts/SpeedManager.cs
Assets/Scripts/Stats.cs
Assets/Scripts/Weapons/BehaviourTypes/BulletMono.cs

- adjusted corespeed
- attached weapon and stats to player, changed it to a prefab
- added speed scaling to player movement, bullets

added speed scaling, player as a prefab.

---

Assets/Resources/Bullet.prefab
Assets/Resources/Player/Player.prefab
Assets/Scripts/Enemy/EnemyFactory.cs

* Remove Player capsule collider, was stopping bullets from hitting the player
* Increase bullet size to 0.3 from 0.1
* Change enemy fire rate to 1/s

Tweak prototype scene and prefabs

---

Assets/Scenes/LevelPrototypeScene.unity

Scaled down  the UI because it was covering the entire screen

Accidentally scaled up the UI too much

---

.vsconfig
Assets/Scenes/LevelPrototypeScene.unity
Assets/Scripts/EnemySpawn.cs

Will write the wave now, figured out how each wave works

Capped the number of enemies

---

Assets/Scripts/Player/PlayerCentral.cs

Changes
* added walljump
Notes
currently because of the implementation of our non-strafing movement we can't actually propel ourselves off of the wall like apex. we are able to gain height though
closes #16

added walljump

---

Assets/Scripts/Player/Movement.cs
Assets/Scripts/Player/PlayerCentral.cs

Changes
* changed dash to resemble a traditional dash with key press, moved to right click
* changed old dash behavior to be a sprint, we can just comment it out for now and decide if we keep it or not later
* changed camera sensitivity to be normal when we build and run the project
Notes
* we should probably chat a bit about keeping sprint or not

revamped dash, changed camera sens, added sprint?

---

Assets/Resources/TreeWalls.prefab
Assets/Scenes/LevelPrototypeScene.unity

added tree walls to scene

---

Assets/Resources/Ranged.prefab

- should now have a collider 
- Screen texture is there maybe?
- Moved it up a little bit

Fixed mech stuff

---

Assets/Materials/HealingPill.mat
Assets/Materials/HealingPill.mat.meta
Assets/Resources/HealingPill.prefab
Assets/Resources/HealingPill.prefab.meta
Assets/Scripts/HealingPill.cs
Assets/Scripts/HealingPill.cs.meta
Assets/Scripts/Stats.cs

Changes
* healing pill drops at a rate of 10% when enemies are killed
* healing pill heals 15 hp

added Healing Pill

---

Assets/Scripts/Globals.cs
Assets/Scripts/HealingPill.cs
Assets/Scripts/Player/Movement.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/PowerUps/AbstractFiringPowerUp.cs

changes
* slowed pill spin animation
* nerfed shotgun powerup
* added dash cooldown and slightly reduced distance
* increase player bullet speed
* updated adrenalin powerup description
* removed sprint

Alpha tweaks

---

Assets/Resources/Grenadier.prefab
Assets/Scenes/LevelPrototypeScene.unity
Assets/Scripts/Enemy/EnemyMovements.cs

changed grenadier distance to 35

Grenadier distance

---

Assets/Scripts/AudioManager.cs
Assets/Scripts/Player/PlayerCentral.cs

Changes
* walljump now has a slight velocity in the direction of the wall's normal (it feels like an actual one)
* fixed null reference error we were getting in audio manager
* dash is now scaled with game speed

revamped walljump, fixed audio null reference

---

Assets/Scripts/SpeedManager.cs
Assets/Scripts/Weapons/BehaviourTypes/ArtilleryAttackBehaviour.cs
Assets/Scripts/Weapons/BehaviourTypes/ArtilleryMono.cs
Assets/Scripts/Weapons/BehaviourTypes/ThermitePoolMono.cs

See https://github.com/MaXeraph/Adrenarun/issues/81
closes #81

Grenadier tweaks

---

Assets/Scripts/Enemy/EnemyFactory.cs
Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/Globals.cs
Assets/Scripts/PowerUps/AbstractFiringPowerUp.cs
Assets/Scripts/PowerUps/PowerUpManager.cs
Assets/Scripts/Weapons/Weapon.cs

Refactors firing mods to belong to each weapon
closes #6

Set targeting

---

Assets/Scripts/Player/PlayerCentral.cs

Changes
* fixed dash in place bug
* dash cd now scales with time

dash cd now scales with time; cannot dash in place anymore

---

Assets/Resources/Grenadier.prefab
Assets/Resources/Ranged.prefab
Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/HealingPill.cs
Assets/Scripts/Player/Movement.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/SpeedManager.cs
Assets/Scripts/Stats.cs

Build before Ubi playtest

---

Assets/Materials/Translucent.mat
Assets/Materials/Translucent.mat.meta
Assets/Resources/Artillery.prefab
Assets/Resources/Bullet.prefab
Assets/Resources/MeleeTank.prefab
Assets/Resources/MeleeTank.prefab.meta
Assets/Resources/ThermitePool.prefab
Assets/Scripts/Enemy/EnemyBehaviour.cs
Assets/Scripts/Enemy/EnemyFactory.cs
Assets/Scripts/Enemy/EnemyMovements.cs
Assets/Scripts/Enemy/EnemySpawn.cs
Assets/Scripts/Globals.cs
Assets/Scripts/ObjectPool.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/Stats.cs
Assets/Scripts/Weapons/BehaviourTypes/BulletMono.cs
Assets/Scripts/Weapons/BehaviourTypes/SweepAttackBehaviour.cs
Assets/Scripts/Weapons/BehaviourTypes/SweepAttackBehaviour.cs.meta
Assets/Scripts/Weapons/BulletAttackBehaviour.cs
Assets/Scripts/Weapons/ShieldBehaviour.cs
Assets/Scripts/Weapons/ShieldBehaviour.cs.meta

Melee tanks that spawn are only shield variants currently.
closes #85

Melee tank

---

Assets/Scripts/Globals.cs
Assets/Scripts/PowerUps/AbstractBulletPowerUp.cs
Assets/Scripts/PowerUps/PowerUpManager.cs
Assets/Scripts/Weapons/AbstractAttackBehaviour.cs
Assets/Scripts/Weapons/BehaviourTypes/BulletMono.cs
Assets/Scripts/Weapons/BulletAttackBehaviour.cs

Changes
* Exploding and Piercing powerups have been added
* Homing powerups is being cut because of scope
closes #23

Bullet powerups

---

Assets/Scripts/PowerUps/AbstractBulletPowerUp.cs
Assets/Scripts/PowerUps/PowerUpManager.cs

Changes
* added piercing and exploding to the tiered powerup generation
* removed a debug statement

added piercing and exploding to the tiered pool

---

Assets/Scenes/Levels/Level 6.unity

In level 6, tree walls were not on the edge of the platform, so some spawnable/navigable area was outside of the arena. This PR moves the tree walls to fix that.

Level 6: Ensure tree walls are on edge of platform

---

Assets/Scripts/PowerUps/PowerUpManager.cs

missed change when tutorial was implemented
present powerups now has a default value

tutorial powerup fix

---

Assets/Scripts/Enemy/WaveManager.cs
Assets/Scripts/LevelTransition.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/SpeedManager.cs

Changes 
* increased player bullet speed by 1.5x
* heals 10 health after each wave
* added 2x movement speed bonus for the player to reach the portal
* increased min speed to 35%
closes #157

Playtesting report changes

---

Assets/Scripts/Globals.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/PowerUps/PowerUpManager.cs
Assets/Scripts/PowerUps/StatPowerUp.cs
Assets/Scripts/Tutorial/TutorialManager.cs

Changes
* added dash cd powerup, it reduces dash cd by 20%
* reformatted PowerUpManager.cs to use tabs
closes #166

Dashcd powerup

---

Assets/Resources/Shield.prefab
Assets/Resources/Shield.prefab.meta
Assets/Resources/Tank.prefab
Assets/Scripts/Enemy/EnemyFactory.cs
Assets/Scripts/Enemy/EnemyMovements.cs
Assets/Scripts/Enemy/WaveManager.cs
Assets/Scripts/Globals.cs
Assets/Scripts/Stats.cs

Re-implemented shield variant for tanks. Added aggressor variant that sets HP to 100 and has 14 movespeed instead of 8.
Variants spawn with equal probability.
Tank damage changed from 10 per 0.1s to 30 per 1s.
Closes #154

Tank types

---

Assets/Scripts/UI/deathUI.cs

Changes
* TransitionPowerUpDictionary wasn't correctly being reloaded on retry

Powerup retry bug

---

Assets/Scripts/HealingPill.cs

Changes
* fixed healing pill clear getting game stuck at 0/10

fix 0/10 bug

---

Assets/Scripts/Enemy/SpawnManager.cs
Assets/Scripts/Enemy/WaveManager.cs

- Turrets spawn close to center of map
- Grenadiers spawn around edge of map
- Tanks occasionally spawn in front of player

Spawn funcs

---

Assets/Scenes/Levels/Level 3.unity

there were some overlapping portals that did weird stuff

Fixed portals in level 3

---

Assets/Scripts/Globals.cs
Assets/Scripts/LevelTransition.cs
Assets/Scripts/Player/PlayerCentral.cs
Assets/Scripts/Tutorial/TutorialManager.cs

Health and pills currently do not persist across level transitions.

Persist health and pills across levels
